src/src/Entity/Groupe.php
<?php

namespace App\Entity;

use App\Repository\GroupeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: GroupeRepository::class)]
class Groupe
{
    const CHOIX = ['TD', 'TP', 'CM'];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 2)]
    #[Assert\NotBlank(message: "Le type d'un goupe est obligatoire")]
    #[Assert\Choice(choices: Groupe::CHOIX, message: 'Choisissez un type valide.')]
    private ?string $type = null;

    #[ORM\ManyToMany(targetEntity: Etudiant::class, inversedBy: 'groupes')]
    private Collection $etudiants;

    #[ORM\OneToMany(mappedBy: 'groupe', targetEntity: Cour::class)]
    private Collection $cours;

    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
        $this->cours = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getFormation() : ?Formation
    {
        if($this->getEtudiants()[0] != null)
        {
            return $this->getEtudiants()[0]->getFormation(); 
        }
        return null;
    }

    /**
     * @return Collection<int, Etudiant>
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants->add($etudiant);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        $this->etudiants->removeElement($etudiant);

        return $this;
    }

    /**
     * @return Collection<int, Cour>
     */
    public function getCours(): Collection
    {
        return $this->cours;
    }

    public function addCour(Cour $cour): self
    {
        if (!$this->cours->contains($cour)) {
            $this->cours->add($cour);
            $cour->setGroupe($this);
        }

        return $this;
    }

    public function removeCour(Cour $cour): self
    {
        if ($this->cours->removeElement($cour)) {
            // set the owning side to null (unless already changed)
            if ($cour->getGroupe() === $this) {
                $cour->setGroupe(null);
            }
        }

        return $this;
    }
}

src/src/Controller/UEValideController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ueValide', name: 'ueValide_')]
class UEValideController extends AbstractController
{

    #[Route('', name: 'index')]
    public function index(EntityManagerInterface $entityManagerInterface): Response
    {
        if($this->getUser()->getEtudiant() == null)
        {
            return $this->render('ue_valide/index.html.twig', ['pasEtudiant' => 42]);
        }
        $etudiantID = $this->getUser()->getEtudiant()->getId();
        $uesValides = $this->getUser()->getEtudiant()->getUesValides();
        //dump($this->getUser());
        //dump($etudiantID);
        //dump($uesValides->toArray());
        return $this->render('ue_valide/index.html.twig', ['list_ues' => $uesValides->toArray()]);
    }

}

src/templates/ue_valide/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Ues validés{% endblock %}

{% block body %}
    {% if pasEtudiant is defined %}
        <h2>Vous n'êtes pas un étudiant!!</h2>
    {% else %}

        {% if list_ues is empty %}
            <h2>Aucun UE validé :(</h2>
        {% else %}
            <h2>Vos Ues validés:</h2>
            <table class="table table-hover table-striped">
                <tr>
                    <th>Nom</th>
                    <th>Volume horaire</th>
                    <th>Spécialité</th>
                    <th>Cursus</th>
                    <th>Formation</th>
                </tr>
                {% for ue in list_ues %}
                    <tr>
                        <td>{{ ue.nom }}</td>
                        <td>{{ ue.volumeHoraire }}</td>
                        <td>{{ ue.specialite.nom }}</td>
                        <td>{{ ue.formation.cursus.nom }}</td>
                        <td>{{ ue.formation.nom }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    {% endif %}
{% endblock %}